# Site settings
title: "The Thought Stream"
author: "Omar Ziranhua"
description: "A place to capture snippets of moments"
keywords: "Philosophy"
biography: "Aparesco!"
colophon: "© MMXIII — MMXVI by Omar Ziranhua.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: ""

twitter_username: magicrootz
github_username: omizzy
linkedin_username: omar-ziranhua
facebook_username: 
google-analytics: 

simple_search: 
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
